### ISSUE TITLE
idea:  http://gis-lab.info/projects/osm_dump/  extracts

### ISSUE THREAD

**Issue by ImreSamu** [julien-noblet/download-geofabrik#32]
gis-lab.info also have a daily osm.pbf extracts (  Russia related  )
* html frontend: http://gis-lab.info/projects/osm_dump/
* dump directory:  http://be.gis-lab.info/data/osm_dump/dump/
* poly info : https://github.com/nextgis/osmdump_poly

**Comment by julien-noblet** [comment]
Since frontend host, files host and poly host are differents I have to add some features to the yml config file.

I'm thinking about something like this : 
```yaml
baseURL: http://gis-lab.info/projects/osm_dump/
formats:
  osm.pbf:
    ext: osm.pbf
    loc: -latest.osm.pbf
    baseURL: http://be.gis-lab.info/data/osm_dump/dump/
  poly:
    ext: poly
    loc: poly
    baseURL: https://github.com/nextgis/osmdump_poly
elements:
...
```
